Style/LineLength:
  Description: 'Limit lines to 130 characters.'
  Max: 130
Style/SpaceInsideParens:
  Enabled: false
Style/SpaceBeforeBlockBraces:
  Enabled: false
StringLiterals:
  Enabled: false
Style/TrailingComma:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/SpaceBeforeComma:
  Enabled: false
