language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
bundler_args: --jobs=2
before_script:
script:
  - bundle exec rspec
branches:
  only:
    - master
notifications:
  email: false
matrix:
  allow_failures:
    - rvm: 2.2
    - rvm: ruby-head
