script: ./script/build_success.sh
after_acript: ./script/build_finish.sh
work_dir: tmp/paraduct_workspace
variables:
  RUBY:
    - 1.9.3
    - 2.0.0
    - 2.1.2
  DATABASE:
    - mysql
    - postgresql
  RAILS:
    - 3.2.0
    - 4.0.0
    - 4.1.0
max_threads: 4
rsync_option:
  exclude_from: .paraduct_rsync_exclude.txt
